// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Project struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Staff struct {
	ID         int     `json:"id"`
	Name       *string `json:"name,omitempty"`
	Department *string `json:"department,omitempty"`
	Role       *string `json:"role,omitempty"`
}

type StaffInput struct {
	Name       string  `json:"name"`
	Department *string `json:"department,omitempty"`
	Role       *string `json:"role,omitempty"`
}

type Task struct {
	ID          int       `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Detail      *string   `json:"detail,omitempty"`
	User        *Staff    `json:"user,omitempty"`
	Status      *string   `json:"status,omitempty"`
	Project     *Project  `json:"project,omitempty"`
	Location    *Location `json:"location,omitempty"`
	Staff       []*Staff  `json:"staff,omitempty"`
}

type TaskInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Detail      *string `json:"detail,omitempty"`
	UserID      *int    `json:"userID,omitempty"`
	Status      *string `json:"status,omitempty"`
	ProjectID   *int    `json:"projectID,omitempty"`
	LocationID  *int    `json:"locationID,omitempty"`
	StaffIDs    []*int  `json:"staffIDs,omitempty"`
}
